name: "update-git-submodules"
description: "Update git submodule(s) to their latest commit or tag"
author: "sgoudham"

inputs:
  gitmodulesPath:
    description: "The path to the '.gitmodules' file. Defaults to '.gitmodules' in the root of the repository."
    required: false
    default: ".gitmodules"
  strategy:
    description: "The strategy to use when updating the submodules, can be either 'commit' or 'tag'. Defaults to 'commit'"
    required: false
    default: "commit"
  submodules:
    description: "The submodules to update. Defaults to all submodules in the '.gitmodules' file."
    required: false
    default: ""

outputs:
  json:
    description: "A JSON array containing all the submodules that were updated."
  matrix:
    description: "A JSON array containing all the submodules that were updated, intended for use in a GitHub Actions matrix strategy."
  prBody:
    description: "A Markdown string containing a formatted table of all the submodules that were updated, intended for use in a pull request body."

runs:
  using: node20
  main: dist/index.js

branding:
  icon: "git-branch"
  color: "red"
