import { SubmoduleWithLatestTag } from "./main";

const header = () => "This PR updates the following submodules:";

const footer = () =>
  "---\n\nThis PR was generated by [sgoudham/update-git-submodules](https://github.com/sgoudham/update-git-submodules).";

const tableHeader = () =>
  "| **Submodule Name** | **Submodule Path** | **Change** |\n| --- | --- | --- |";

const tableRow = (submodule: SubmoduleWithLatestTag) => {
  const name = `[${submodule.name}](${submodule.url})`;
  const cleanUrl = submodule.url.replace(".git", "");
  const changeTagDisplay = `${submodule.previousTag}...${submodule.latestTag}`;
  const changeUrl = `[${changeTagDisplay}](${cleanUrl}/compare/${changeTagDisplay})`;
  return `| ${name} | ${submodule.path} | ${changeUrl} |`;
};

const singleTable = (submodule: SubmoduleWithLatestTag) => {
  return `${tableHeader()}\n${tableRow(submodule)}`;
};

const multipleTable = (submodules: SubmoduleWithLatestTag[]) => {
  const body = submodules.map((submodule) => tableRow(submodule)).join("\n");
  return `${tableHeader()}\n${body}`;
};

export const singlePrBody = (submodule: SubmoduleWithLatestTag) => {
  return `${header()}\n${singleTable(submodule)}\n${footer()}`;
};

export const multiplePrBody = (submodules: SubmoduleWithLatestTag[]) => {
  return `${header()}\n${multipleTable(submodules)}\n${footer()}`;
};
