import { Submodule } from "./main";

const header = () => "This PR updates the following submodules:";

const footer = () =>
  "---\n\nThis PR was generated by [sgoudham/update-git-submodules](https://github.com/sgoudham/update-git-submodules).";

const tableHeader = () =>
  "| **Remote Repository** | **Submodule Path** | **Change** |\n| --- | --- | --- |";

const tableRow = (submodule: Submodule) => {
  const name = `[${submodule.remoteName}](${submodule.url})`;
  const cleanUrl = submodule.url.replace(".git", "");
  let changeDisplay = `${submodule.previousShortCommitSha}...${submodule.latestShortCommitSha}`;
  let changeUrl = `[${changeDisplay}](${cleanUrl}/compare/${submodule.previousCommitSha}...${submodule.latestCommitSha})`;

  if (submodule.latestTag) {
    if (submodule.previousCommitShaHasTag) {
      changeDisplay = `${submodule.previousTag}...${submodule.latestTag}`;
      changeUrl = `[${changeDisplay}](${cleanUrl}/compare/${changeDisplay})`;
    } else {
      changeDisplay = `${submodule.previousShortCommitSha}...${submodule.latestTag}`;
      changeUrl = `[${changeDisplay}](${cleanUrl}/compare/${submodule.previousCommitSha}...${submodule.latestTag})`;
    }
  }

  return `| ${name} | ${submodule.path} | ${changeUrl} |`;
};

const singleTable = (submodule: Submodule) => {
  return `${tableHeader()}\n${tableRow(submodule)}`;
};

const multipleTable = (submodules: Submodule[]) => {
  const body = submodules.map((submodule) => tableRow(submodule)).join("\n");
  return `${tableHeader()}\n${body}`;
};

export const singlePrBody = (submodule: Submodule) => {
  return `${header()}\n${singleTable(submodule)}\n${footer()}`;
};

export const multiplePrBody = (submodules: Submodule[]) => {
  return `${header()}\n${multipleTable(submodules)}\n${footer()}`;
};
